"""Brings the Blender kit into Unreal: materials first, then meshes, then slots.

The kit is generated by Scripts/Make-Kit.py (which runs in the cloud, in
Blender-as-a-library) and lands in Art/Kit as one FBX per piece plus kit.json.
This script is the other half: it makes the materials, imports the meshes, and
wires the two together.

THREE THINGS IT DOES ON PURPOSE, EACH ONE A BUG WE ALREADY PAID FOR
--------------------------------------------------------------------
* **Every material is created with `used_with_instanced_static_meshes`.** A
  material without that flag is silently replaced by the engine's plain grey
  whenever it is drawn through a HISM -- and the whole world is drawn through
  HISMs. That flag missing on four pack materials is what "um piso cinza"
  turned out to be, after a day spent theorising about water shaders.
* **Import settings are written out in full rather than left to the defaults.**
  The editor remembers the last FBX dialog you used, so "the defaults" are
  whoever's last import, which is not a thing a script may rely on.
* **It prints a count of every step and refuses to be quiet.** A commandlet's
  exit code is the number of logged Errors, not a verdict.

Idempotent: re-running re-imports over the same assets.
"""
import json
import os
import importlib.util

import unreal

HERE     = os.path.dirname(os.path.abspath(__file__))
collision_spec = importlib.util.spec_from_file_location('kit_collision', os.path.join(HERE, 'Kit-Collision.py'))
collision_module = importlib.util.module_from_spec(collision_spec)
collision_spec.loader.exec_module(collision_module)
ART      = os.path.normpath(os.path.join(HERE, "..", "Art", "Kit"))
MESH_DIR = "/Game/AshenHollow/Kit/Meshes"
MAT_DIR  = "/Game/AshenHollow/Kit/Materials"

assets  = unreal.AssetToolsHelpers.get_asset_tools()
library = unreal.EditorAssetLibrary
ME      = unreal.MaterialEditingLibrary

PROBLEMS = []


def say(message):
    unreal.log("AH_KIT %s" % message)


def bad(message):
    PROBLEMS.append(message)
    unreal.log_warning("AH_KIT PROBLEMA: %s" % message)


manifest_path = os.path.join(ART, "kit.json")
if not os.path.isfile(manifest_path):
    bad("nao achei %s -- o kit nao foi copiado para Art/Kit" % manifest_path)
    unreal.log_warning("AH_KIT ABORTADO")
    raise SystemExit

with open(manifest_path, "r", encoding="utf-8") as handle:
    manifest = json.load(handle)
say("manifesto com %d pecas e %d materiais"
    % (len(manifest["pieces"]), len(manifest["palette"])))

# What finish() in Make-Kit.py averaged over every face it baked. Older
# manifests do not carry it, and 1.0 is the honest fallback: the kit simply
# comes out as dark as it was baked rather than silently wrong.
GRAIN_GAIN = 1.0 / float(manifest.get("grain_centre") or 1.0)
say("ganho do grao: x%.3f" % GRAIN_GAIN)


# ── Materials ──────────────────────────────────────────────────────────────
def make_material(name, spec):
    path = "%s/%s" % (MAT_DIR, name)
    material = library.load_asset(path)
    if not material:
        material = assets.create_asset(name, MAT_DIR, unreal.Material,
                                       unreal.MaterialFactoryNew())
    if not material:
        bad("nao consegui criar %s" % path)
        return None

    ME.delete_all_material_expressions(material)

    red, green, blue = spec["rgb"]
    colour = ME.create_material_expression(
        material, unreal.MaterialExpressionVectorParameter, -420, 0)
    colour.set_editor_property("parameter_name", "Cor")
    colour.set_editor_property("default_value",
                               unreal.LinearColor(red, green, blue, 1.0))
    # Base colour TIMES the mesh's own per-face shading.
    #
    # Nine flat colours and nothing else is what "as texturas ainda estao cor
    # cinza" was: a stone wall really was one unbroken grey rectangle. The
    # variation is baked per face in Blender, costs no texture memory and no
    # sampler, and turns that rectangle into a wall of individually lit
    # stones. It is the oldest trick in low-poly and the reason the style
    # works at all.
    grain = ME.create_material_expression(
        material, unreal.MaterialExpressionVertexColor, -420, 380)
    # Divided back out by what the bake averaged.
    #
    # An eight-bit vertex colour cannot exceed 1.0, so the variation has to be
    # baked BELOW one and lifted here -- otherwise half the faces clamp and
    # stop varying, which is exactly what the first attempt did: 0.84 to 1.14
    # became 0.84 to 1.00 with most of the kit sitting on the ceiling, and it
    # was invisible. Now it is baked around %.3f and multiplied by 1 / %.3f,
    # so the average colour on screen is exactly the palette and the variation
    # rides on top of it. Art/Kit/kit.json carries the number, measured over
    # every face the kit has, so the two can never drift apart.
    lift = ME.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -300, 380)
    assert ME.connect_material_expressions(grain, "", lift, "A")
    lift.set_editor_property("const_b", GRAIN_GAIN)
    shaded = ME.create_material_expression(
        material, unreal.MaterialExpressionMultiply, -180, 0)
    assert ME.connect_material_expressions(colour, "RGB", shaded, "A")
    assert ME.connect_material_expressions(lift, "", shaded, "B")
    assert ME.connect_material_property(shaded, "", unreal.MaterialProperty.MP_BASE_COLOR)

    if name in ('M_Kit_folha', 'M_Kit_folha2'):
        time = ME.create_material_expression(material, unreal.MaterialExpressionTime, -600, 700)
        speed = ME.create_material_expression(material, unreal.MaterialExpressionMultiply, -420, 700)
        speed.set_editor_property('const_b', .23)
        assert ME.connect_material_expressions(time, '', speed, 'A')
        wave = ME.create_material_expression(material, unreal.MaterialExpressionSine, -240, 700)
        assert ME.connect_material_expressions(speed, '', wave, '')
        direction = ME.create_material_expression(material, unreal.MaterialExpressionConstant3Vector, -240, 900)
        direction.set_editor_property('constant', unreal.LinearColor(5, 3, 1, 0))
        sway = ME.create_material_expression(material, unreal.MaterialExpressionMultiply, -60, 700)
        assert ME.connect_material_expressions(wave, '', sway, 'A')
        assert ME.connect_material_expressions(direction, '', sway, 'B')
        assert ME.connect_material_property(sway, '', unreal.MaterialProperty.MP_WORLD_POSITION_OFFSET)

    rough = ME.create_material_expression(
        material, unreal.MaterialExpressionScalarParameter, -420, 200)
    rough.set_editor_property("parameter_name", "Aspereza")
    rough.set_editor_property("default_value", spec["roughness"])
    ME.connect_material_property(rough, "", unreal.MaterialProperty.MP_ROUGHNESS)

    if spec.get("emissive"):
        glow = ME.create_material_expression(
            material, unreal.MaterialExpressionMultiply, -220, 400)
        ME.connect_material_expressions(colour, "RGB", glow, "A")
        glow.set_editor_property("const_b", 6.0)
        ME.connect_material_property(glow, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)

    # The flag. Without it the engine swaps this material for plain grey the
    # moment it is drawn as an instance, and says so only in the log.
    for flag in ("used_with_instanced_static_meshes", "used_with_static_lighting"):
        try:
            material.set_editor_property(flag, True)
        except Exception as error:                               # noqa: BLE001
            say("   (nao consegui marcar %s em %s: %s)" % (flag, name, error))

    ME.recompile_material(material)
    library.save_loaded_asset(material, only_if_is_dirty=False)
    return material


palette = {}
for name, spec in manifest["palette"].items():
    made = make_material(name, spec)
    if made:
        palette[name] = made
say("%d materiais prontos" % len(palette))


# ── The one material that is not for the kit ───────────────────────────────
def make_body_material():
    """A flat, tintable body material for every character in the game.

    WHY IT IS HERE. Lucas, twice: "muitas texturas ainda continuam cinza". By
    now the scenery is twenty-four colours with per-face shading, and the log
    says every mesh got its material -- so the grey he is looking at is the
    PEOPLE. The hero, up to eighteen foes and ten villagers are all the same
    untextured UE5 mannequin, which is literally grey plastic, and they are
    what moves and what the eye follows.

    WHY IT IS FLAT. A vertical two-tone gradient (trousers, tunic) would look
    better and needs WorldPosition, ActorPositionWS, masks and a lerp -- six
    engine expression classes I cannot compile or test from here, in a script
    that runs once inside the editor. This uses exactly the two expression
    types the kit materials already use and are proved to work. A field of
    people in twelve different colours is most of the win; the gradient can
    come later, once somebody has seen this one render.

    AND THE FLAG. `used_with_skeletal_mesh` is the whole reason this cannot be
    one of the kit materials: without it the engine silently swaps in the plain
    grey default the moment it is drawn on a skeleton, and says so only in the
    log. That is bug 8 of this project, in a new costume.
    """
    name = "M_AH_Corpo"
    path = "%s/%s" % (MAT_DIR, name)
    material = library.load_asset(path)
    if not material:
        material = assets.create_asset(name, MAT_DIR, unreal.Material,
                                       unreal.MaterialFactoryNew())
    if not material:
        bad("nao consegui criar %s" % path)
        return None
    try:
        ME.delete_all_material_expressions(material)
    except Exception:                                            # noqa: BLE001
        pass

    colour = ME.create_material_expression(
        material, unreal.MaterialExpressionVectorParameter, -420, 0)
    colour.set_editor_property("parameter_name", "Cor")
    colour.set_editor_property("default_value",
                               unreal.LinearColor(0.60, 0.58, 0.54, 1.0))
    ME.connect_material_property(colour, "RGB", unreal.MaterialProperty.MP_BASE_COLOR)

    rough = ME.create_material_expression(
        material, unreal.MaterialExpressionScalarParameter, -420, 200)
    rough.set_editor_property("parameter_name", "Aspereza")
    rough.set_editor_property("default_value", 0.72)
    ME.connect_material_property(rough, "", unreal.MaterialProperty.MP_ROUGHNESS)

    for flag in ("used_with_skeletal_mesh", "used_with_static_lighting",
                 "used_with_morph_targets"):
        try:
            material.set_editor_property(flag, True)
        except Exception as error:                               # noqa: BLE001
            say("   (nao consegui marcar %s em %s: %s)" % (flag, name, error))

    ME.recompile_material(material)
    library.save_asset(path)
    say("material de corpo pronto em %s" % path)
    return material


make_body_material()


# ── Meshes ─────────────────────────────────────────────────────────────────
def import_options():
    options = unreal.FbxImportUI()
    options.set_editor_property("import_mesh", True)
    options.set_editor_property("import_textures", False)
    options.set_editor_property("import_materials", False)
    options.set_editor_property("import_as_skeletal", False)
    options.set_editor_property("mesh_type_to_import",
                                unreal.FBXImportType.FBXIT_STATIC_MESH)
    data = options.static_mesh_import_data
    data.set_editor_property("combine_meshes", True)
    data.set_editor_property("generate_lightmap_u_vs", True)
    # OFF, and this is the whole reason the kit now ships UCX boxes.
    #
    # An auto-generated hull wraps whatever the asset contains. For a tree
    # that is the canopy: a five-metre invisible cylinder standing in the
    # middle of every wood, which is what "problemas pra se mover
    # especialmente perto de arvores" was -- the player walking into the
    # shadow of the leaves. For a house it is the roof overhang; for an arch
    # it fills in the gap you are supposed to walk through.
    #
    # Every FBX now carries UCX_<name>_NN objects modelled beside the mesh,
    # and by default they are a box of the piece's DECLARED FOOTPRINT. So what
    # stops you is exactly the rectangle the piece was modelled inside.
    data.set_editor_property("auto_generate_collision", False)
    data.set_editor_property("remove_degenerates", True)
    # The per-face shading is baked into a vertex colour layer in Blender, and
    # an import that drops it throws away the only thing standing between a
    # stone wall and one flat grey rectangle.
    try:
        data.set_editor_property(
            "vertex_color_import_option",
            unreal.VertexColorImportOption.REPLACE)
    except Exception as error:                                   # noqa: BLE001
        say("   (nao consegui pedir as cores de vertice: %s)" % error)
    data.set_editor_property("convert_scene", True)
    data.set_editor_property("force_front_x_axis", False)
    data.set_editor_property("import_uniform_scale", 1.0)
    return options


tasks = []
for piece in manifest["pieces"]:
    source = os.path.join(ART, piece["fbx"])
    if not os.path.isfile(source):
        bad("faltando %s" % piece["fbx"])
        continue
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", source)
    task.set_editor_property("destination_path", MESH_DIR)
    task.set_editor_property("destination_name", piece["name"])
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("save", True)
    task.set_editor_property("options", import_options())
    tasks.append(task)

if tasks:
    assets.import_asset_tasks(tasks)
say("%d malhas importadas" % len(tasks))


# ── Slots ──────────────────────────────────────────────────────────────────
# The FBX carries material NAMES but no materials, so the imported mesh has a
# slot per name pointing at nothing useful. Matching them here by name is what
# turns forty grey meshes into the kit.
dressed, missing = 0, 0
for piece in manifest["pieces"]:
    path = "%s/%s" % (MESH_DIR, piece["name"])
    mesh = library.load_asset(path)
    if not mesh:
        bad("nao carregou %s" % path)
        continue
    slots = mesh.get_editor_property("static_materials")
    changed = False
    for slot_index, slot in enumerate(slots):
        wanted = str(slot.material_slot_name)
        material = palette.get(wanted)
        if material is None:
            # Blender appends .001 when a name repeats; the stem is the name.
            material = palette.get(wanted.split(".")[0])
        if material is None:
            missing += 1
            bad("%s slot %s sem material" % (piece['name'], wanted))
            continue
        # StaticMaterial values returned through Python are copies. Use the mesh
        # API to notify the asset and dirty its package before saving.
        mesh.set_material(slot_index, material)
        changed = True
    if changed:
        library.save_loaded_asset(mesh, only_if_is_dirty=False)
        dressed += 1
    collision_module.apply_collision(mesh, piece)
say("%d malhas com materiais aplicados (%d espacos sem material)" % (dressed, missing))


# ── Did the collision come across? ─────────────────────────────────────────
# Asked rather than assumed. If the UCX boxes did not import, every tree is
# walk-through and every wall is scenery, and nothing else in the game would
# say so. The API for counting them has moved between engine versions, so the
# candidates are tried in turn and the one that answers is named.
def collision_count(mesh):
    geom = mesh.get_editor_property('body_setup').get_editor_property('agg_geom')
    return sum(len(geom.get_editor_property(kind)) for kind in
               ('box_elems', 'convex_elems', 'sphere_elems', 'sphyl_elems')), 'BodySetup'


counted, bare, how = 0, [], None
for piece in manifest["pieces"]:
    mesh = library.load_asset("%s/%s" % (MESH_DIR, piece["name"]))
    if not mesh:
        continue
    shapes, label = collision_count(mesh)
    if shapes is None:
        break
    how = label
    counted += 1
    if shapes != len(piece['collision']):
        bad('%s: expected %d collision boxes, got %d' % (piece['name'], len(piece['collision']), shapes))
    if shapes == 0:
        bare.append(piece["name"])
if how:
    say("colisao conferida por %s: %d malhas" % (how, counted))
    if bare:
        bad("sem colisao nenhuma: %s" % ", ".join(bare[:10]))
else:
    say("nao consegui contar a colisao nesta build -- confira uma malha a mao")

if PROBLEMS:
    unreal.log_warning("AH_KIT terminou com %d problema(s):" % len(PROBLEMS))
    for problem in PROBLEMS:
        unreal.log_warning("AH_KIT   - %s" % problem)
    raise RuntimeError('Kit import failed: ' + '; '.join(PROBLEMS))
else:
    unreal.log("AH_KIT tudo certo. O kit esta em %s" % MESH_DIR)
